### ISSUE TITLE
the meaning of "# * @" in light/heavy chemical composition files.

### ISSUE THREAD

**Issue by liuzan-info** [wangchulab/CIMAGE_Lite#1]
Great job. I have a query now. I have a custom probe, and I want to modify the configuration file, but I am unsure about the meaning of the last three lines. Thank you for your assistance.

![image](https://github.com/user-attachments/assets/7b8ab935-dc97-4966-b353-241dbcefc019)

**Comment by wendao** [comment]
Hi, Thank you for your interest. These symbols correspond to modifications on peptides. This notation comes from the older output of sequest/prolucid software. When we process outputs from other software, we standardize the coding to this format.

They are all variable modifications and should match your searching scheme

For example: AAAM#AAA, means Oxidation modification on M.
